[package]
name = "service-api"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1.38.0", features = ["full"] }
sqlx = { version = "0.7", features = ["postgres", "runtime-tokio", "macros"] }

